### PR TITLE
Upgrade to version 0.77

### PR DESCRIPTION
**Pull request by fschloesser**
Upgrading the code to the latest version 0.77 downloadable from https://users.aalto.fi/~tjunttil/bliss/download.html.
Currently tested on a linux and windows machine.

### CODE REVIEW

**Comment by fschloesser** [comment]
I just saw that the install section from the CMakeLists.txt got lost, will add this next week, but hopefully that shouldn't jumble up things

**Comment by fschloesser** [comment]
I consider this ready now. It builds now on my linux machine also with scip, and it does build on windows and mac.

**Comment by fschloesser** [comment]
@jdumouchelle @AntoinePrv is something missing here or can we merge this?

**Comment by AntoinePrv** [comment]
Hi @fschloesser , I think I let you manage this, I think you'll be a better judge.

**Pull request merged**
